name: Checkpoint FeeDistributor

on:
  schedule:
    - cron: "0 0 * * 4"
  workflow_dispatch:

jobs:
  checkpoint-feedistributor:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - id: df-py
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: oceanprotocol
          repo: df-py
          excludes: prerelease, draft

      - name: Set branch to checkout
        id: set_branch
        run: echo "BRANCH=${{ github.event_name == 'schedule' && steps.df-py.outputs.release || github.ref }}" >> $GITHUB_ENV

      - uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH }}

      - name: Set up Python {{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        working-directory: ${{ github.workspace }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --quiet

      - name: Set up Openzeppelin
        run: |
          brownie pm install OpenZeppelin/openzeppelin-contracts@4.2.0
          brownie pm install GNSPS/solidity-bytes-utils@0.8.0

      - name: Set env variables
        run: |
          echo "DFTOOL_KEY=${{ secrets.DFTOOL_KEY_MULTISIG }}" >> $GITHUB_ENV
          echo "ADDRESS_FILE=.github/workflows/data/address.json" >> $GITHUB_ENV
          echo "WEB3_INFURA_PROJECT_ID=${{ secrets.WEB3_INFURA_PROJECT_ID }}" >> $GITHUB_ENV

      - name: Make dftool executable
        run: chmod +x dftool

      - name: Run dftool checkpoint_feedist
        run: |
          ./dftool checkpoint_feedist 1
