name: Dispense Active Rewards

on:
  schedule:
    - cron: "0 0 * * 4"
  workflow_dispatch:
    inputs:
      amt_of_tokens:
        description: "Amount of tokens to distribute"
        required: true
        default: "10000"

jobs:
  
  # we already have a test flow in test.yml
  # re-use that flow
  run-tests:
    uses: ./.github/workflows/test.yml

  dispense-active:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    needs: run-tests
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python {{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        working-directory: ${{ github.workspace }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --quiet

      - name: Set up Openzeppelin
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          brownie pm install OpenZeppelin/openzeppelin-contracts@4.2.0
          brownie pm install GNSPS/solidity-bytes-utils@0.8.0

      - name: Add networks to brownie
        run: |
          brownie networks add moonbase moonbase host=https://rpc.api.moonbase.moonbeam.network chainid=1287
          brownie networks add mumbai mumbai host=https://matic-mumbai.chainstacklabs.com chainid=80001
          brownie networks add energyweb energyweb host=https://rpc.energyweb.org chainid=246
          brownie networks add polygon polygon host=https://polygon-rpc.com/ chainid=137
          brownie networks add bsc bsc host=https://bsc-dataseed1.binance.org chainid=56
          brownie networks add moonriver moonriver host=https://rpc.api.moonriver.moonbeam.network chainid=1285

      - name: Set env variables
        run: |
          echo "DFTOOL_KEY=${{ secrets.DFTOOL_KEY_MULTISIG }}" >> $GITHUB_ENV
          echo "ADDRESS_FILE=.github/workflows/data/address.json" >> $GITHUB_ENV
          echo "WEB3_INFURA_PROJECT_ID=${{ secrets.WEB3_INFURA_PROJECT_ID }}" >> $GITHUB_ENV
          echo "SECRET_SEED=${{ secrets.SECRET_SEED }}" >> $GITHUB_ENV
          echo "date=$(date -dlast-thursday '+%Y-%m-%d')" >> $GITHUB_ENV
          echo "now=$(date '+%Y-%m-%d')" >> $GITHUB_ENV
          echo "CSV_DIR=/tmp/csv" >> $GITHUB_ENV
          echo "RETRY_TIMES=5" >> $GITHUB_ENV

      - name: Run dftool getrate
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          ./dftool getrate OCEAN $date $now $CSV_DIR $RETRY_TIMES
          ./dftool getrate ETH $date $now $CSV_DIR $RETRY_TIMES
          ./dftool getrate BNB $date $now $CSV_DIR $RETRY_TIMES
          ./dftool getrate EWT $date $now $CSV_DIR $RETRY_TIMES
          ./dftool getrate MOVR $date $now $CSV_DIR $RETRY_TIMES
          ./dftool getrate MATIC $date $now $CSV_DIR $RETRY_TIMES

      - name: Run dftool volsym
        run: |
          ./dftool volsym $date $now 200 $CSV_DIR 1 $RETRY_TIMES
          ./dftool volsym $date $now 200 $CSV_DIR 56 $RETRY_TIMES
          ./dftool volsym $date $now 200 $CSV_DIR 137 $RETRY_TIMES
          ./dftool volsym $date $now 200 $CSV_DIR 246 $RETRY_TIMES
          ./dftool volsym $date $now 200 $CSV_DIR 1285 $RETRY_TIMES

      - name: Run dftool vebals
        run: |
          ./dftool vebals $date $now 200 $CSV_DIR 1 $RETRY_TIMES

      - name: Run dftool allocations
        run: |
          ./dftool allocations $date $now 200 $CSV_DIR 1 $RETRY_TIMES

      - name: Run sed
        run: |
          cp $CSV_DIR/rate-OCEAN.csv $CSV_DIR/rate-MOCEAN.csv
          sed -i -e 's/MOCEAN/OCEAN/g' $CSV_DIR/rate-MOCEAN.csv

      - name: Run dftool calc
        run: |
          ./dftool calc $CSV_DIR ${{ github.event.inputs.amt_of_tokens || secrets.TOKEN_AMOUNT }} OCEAN

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: CSV Files
          retention-days: 5
          path: /tmp/csv

      - name: Distribute test active rewards
        env:
          USE_MULTISIG: true
        if: github.event_name == 'workflow_dispatch'
        run: |
          ./dftool dispense_active $CSV_DIR 5 0x6fd867E5AEE6D62a24f97939db90C4e67A73A651 0xCfDdA22C9837aE76E0faA845354f33C62E03653a

      - name: Distribute active rewards
        env:
          USE_MULTISIG: true
        if: github.event_name == 'schedule'
        run: |
          ./dftool dispense_active $CSV_DIR 1 0xFe27534EA0c016634b2DaA97Ae3eF43fEe71EEB0 0x967da4048cD07aB37855c090aAF366e4ce1b9F48

      - name: Rename folder to round number
        run: |
          bash ./scripts/workflow_rename_folder.sh

      - id: 'auth'
        if: github.event_name == 'schedule'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GC_SECRET }}'
          #workload_identity_provider: ${{ secrets.GCLOUD_IDENTITY_PROVIDER }}
          #service_account: ${{ secrets.SERVICE_ACCOUNT }}
          
      - id: 'upload-folder'
        if: github.event_name == 'schedule'
        uses: 'google-github-actions/upload-cloud-storage@v1'
        with:
          path: '/tmp/csv/${{ env.DFWEEK }}'
          destination: 'df-historical-data'
