name: Unit Testing and Code Coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_call:

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python {{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/checkout@v2
        name: Checkout Barge
        with:
          repository: "oceanprotocol/barge"
          path: "barge"
          ref: 9cc3a9342a47857a0495309e787462d6c60979e6

      - name: Run Barge
        working-directory: ${{ github.workspace }}/barge
        run: |
          bash -x start_ocean.sh --no-aquarius --no-elasticsearch --no-provider --no-dashboard --with-thegraph > start_ocean.log &
          for i in $(seq 1 108); do
            sleep 5
            [ -f "$HOME/.ocean/ocean-contracts/artifacts/ready" -a -f "$HOME/.ocean/ocean-c2d/ready" ] && break
            done
          ls -la "$HOME/.ocean/ocean-contracts/artifacts/"
        env:
          CONTRACTS_VERSION: v1.1.3
          SUBGRAPH_VERSION: v3.0.7

      - name: Install dependencies
        working-directory: ${{ github.workspace }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          brownie bake github-actions
          sed -i 's#https://polygon-mainnet.infura.io/v3/$WEB3_INFURA_PROJECT_ID#https://polygon-rpc.com/#g; s#https://polygon-mumbai.infura.io/v3/$WEB3_INFURA_PROJECT_ID#https://rpc-mumbai.maticvigil.com#g' $HOME/.brownie/network-config.yaml

      - name: Set up Openzeppelin
        run: |
          brownie pm install OpenZeppelin/openzeppelin-contracts@4.2.0
          brownie pm install GNSPS/solidity-bytes-utils@0.8.0

      - name: Test with Brownie
        run: |
          coverage run --omit="*test*" -m pytest util/test
          coverage report
          coverage xml
        env:
          USE_BINANCE_US: 1
          REMOTE_TEST_PRIVATE_KEY1: ${{secrets.REMOTE_TEST_PRIVATE_KEY1}}
          POLYGONSCAN_API_KEY: ${{secrets.POLYGONSCAN_API_KEY}}

      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
