name: Unit Testing and Code Coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_call:

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python {{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/checkout@v2
        name: Checkout Barge
        with:
          repository: "oceanprotocol/barge"
          path: "barge"
          ref: 9cc3a9342a47857a0495309e787462d6c60979e6

      - name: Run Barge
        working-directory: ${{ github.workspace }}/barge
        run: |
          bash -x start_ocean.sh --no-aquarius --no-elasticsearch --no-provider --no-dashboard --with-thegraph > start_ocean.log &    
        env:
          CONTRACTS_VERSION: v1.1.3
          SUBGRAPH_VERSION: v3.0.7

      - name: Install dependencies
        working-directory: ${{ github.workspace }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Create Brownie paths
        run: |
           mkdir /home/runner/.solcx
           mkdir /home/runner/.vvm
           mkdir -p /home/runner/.brownie/packages
      - name: Restore Brownie compilers
        id: restore-brownie-compilers
        uses: actions/cache/save@v3
        with:
          path: |
            /home/runner/.solcx
            /home/runner/.vvm
            /home/runner/.brownie/packages
          key: ${{ runner.os }}-brownie-deps
      - name: Set up Openzeppelin
        run: |
          [ -d "$HOME/.brownie/packages/OpenZeppelin/openzeppelin-contracts@4.2.0" ] && echo "Using OpenZeppelin/openzeppelin-contracts@4.2.0 from cache" || brownie pm install OpenZeppelin/openzeppelin-contracts@4.2.0
          [ -d "$HOME/.brownie/packages/GNSPS/solidity-bytes-utils@0.8.0" ] && echo "Using GNSPS/solidity-bytes-utils@0.8.0/ from cache" || brownie pm install GNSPS/solidity-bytes-utils@0.8.0
      - name: Make dftool executable
        run: chmod +x dftool

      - name: Wait for contracts deployment
        working-directory: ${{ github.workspace }}/barge
        run: |
          for i in $(seq 1 250); do
            sleep 10
            [ -f "$HOME/.ocean/ocean-contracts/artifacts/ready" ] && break
            done
      - name: Test with Brownie
        run: |
          coverage run --omit="*test*" -m pytest util/test
          coverage report
          coverage xml
      - name: Save Brownie compilers
        id: cache-brownie-compilers
        uses: actions/cache/save@v3
        with:
          path: |
            /home/runner/.solcx
            /home/runner/.vvm
            /home/runner/.brownie/packages
          key: ${{ runner.os }}-brownie-deps
      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
